observation_publisher:
  ros__parameters:
    timer_period: 1.0
    speed: 0.5

    track:
      chosen: 1
      random: false

    # Dimensions according to FSG rules
    cone_dimensions:
      regular:
        radius: 0.714
        height: 1.325
      large:
        radius: 0.1425
        height: 0.505
