path_publisher:
  ros__parameters:
    timer_period: 1.0

    track:
      chosen: 1
      random: true

    cone_dimensions:
      regular:
        radius: 1.0
        height: 1.5
      large:
        radius: 1.5
        height: 3.0
