sim_dynamics:
  ros__parameters:
    model: "hbm"
    init_state: [0., 0., 0.] #[0., 0., 1.5708] # Point straight up
    fps: 60

    # Model specific stuff
    kbm:
      lf: 0.270
      lr: 0.055
      vmax: 5.
    
    hbm:
      mass: 4.75
      Fmax: 5.0
      drag_coeffs: [0.0, 0.5, 0.5]
      lf: 0.270
      lr: 0.055

    dbm:
      mass: 4.75
      Iz: 0.1
      Cf: 50.0
      Cr: 50.0
      drag_coeffs: [0.0, 1.0, 1.0]
      lf: 0.180
      lr: 0.145
